apiVersion: v1
kind: Secret
metadata:
  name: vehicle-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: TXljbG91ZEAyNQ==   # base64 of 'Mycloud@25'
  MYSQL_PASSWORD: TXljbG91ZEAyNQ==         # base64 of 'Mycloud@25'
