apiVersion: v1
kind: ConfigMap
metadata:
  name: vehicle-config
data:
  DB_HOST: mysql-db
  DB_NAME: vehicle_dashboard
  DB_USER: vehicledbuser
  REACT_APP_BACKEND_URL: http://backend-subscriber:5000
