apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  MYSQL_DATABASE: vehicle_dashboard
  MYSQL_USER: vehicledbuser
  DB_HOST: mysql
  DB_USER: vehicledbuser
  DB_NAME: vehicle_dashboard
  REACT_APP_BACKEND_URL: http://backend-service:5000
